version: '2'
services:
    php:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      volumes:
        - ~/.composer-docker/cache:/root/.composer/cache:delegated
        - ./:/app:delegated
      ports:
        - '${APP_PORT:-8000}:80'
      networks:
        - local-network


    mysql:
      image: 'mysql/mysql-server:8.0'
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-developer}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE:-app_db}'
          MYSQL_USER: '${DB_USERNAME:-developer}'
          MYSQL_PASSWORD: '${DB_PASSWORD:-developer}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_TCP_PORT: 3306
      volumes:
          - 'mysql-data:/var/lib/mysql'
      networks:
          - local-network
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-developer}"]
          retries: 3
          timeout: 5s


    mysql-test:
      image: 'mysql/mysql-server:8.0'
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports:
          - '${FORWARD_DB_TEST_PORT:-3307}:3306'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-developer}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE:-app_db_test}'
          MYSQL_USER: '${DB_USERNAME:-developer}'
          MYSQL_PASSWORD: '${DB_PASSWORD:-developer}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_TCP_PORT: 3306
      volumes:
          - 'mysql-test-data:/var/lib/mysql'
      networks: 
          - local-network
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-developer}"]
          retries: 3
          timeout: 5s



    phpmyadmin:
        image: phpmyadmin
        container_name: app_phpmyadmin
        depends_on:
            - mysql
            - mysql-test
        links:
          - mysql
          - mysql-test
        ports:
            - "127.0.0.1:${PHPMYADMIN_PORT:-89}:80"
        environment:
            - PMA_HOST=mysql,mysql-test
            - MYSQL_USERNAME='${DB_USERNAME:-developer}'
            - MYSQL_ROOT_PASSWORD='${DB_PASSWORD:-developer}'
            - PMA_ARBITRARY=0
            - UPLOAD_LIMIT=500M
        volumes:
            - ./docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        networks:
            - local-network




networks:
    local-network:
      driver: bridge
    app-network:
      driver: bridge

volumes:
    mysql-data:
        driver: local
    mysql-test-data:
        driver: local